title: "Junrui Liu - Personal Academic Homepage"
email: "liujunrui@bigc.edu/cn"
description: "Lecturer at BigC"
baseurl: ""
url: "https://dianziliu.github.io"
twitter_username: "your_twitter"
github_username: "dianziliu"
linkedin_username: "your_linkedin"
